<!-- MHonArc v2.6.10 -->
<!--X-Subject: [bug #7863] model_selection('AIC', run,	runs=self.runs) in the script full_analysis.py shoots error -->
<!--X-From-R13: Eéonfgvra [beva <@A&#45;DSBZK.W@HOZWR&#45;ORRDSEENtan.bet> -->
<!--X-Date: Mon, 27 Nov 2006 18:52:28 +0100 -->
<!--X-Message-Id: 20061127&#45;175227.sv7147.87712@gna.org -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>[bug #7863] model_selection('AIC', run,	runs=self.runs) in the script full_analysis.py shoots error -- November 27, 2006 - 18:52</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />[bug #7863] model_selection('AIC', run,	runs=self.runs) in the script full_analysis.py shoots error</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00206" class="tabs">Index by Date</a> | <a href="threads.html#00206" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00205.html">Date Prev</a>] [<a href="msg00207.html">Date Next</a>] [<a href="msg00202.html">Thread Prev</a>] [<a href="msg00209.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: Sébastien Morin &lt;sebastien.morin.1@xxxxxxxxx&gt;,	relax-devel@xxxxxxx</li>
<li class="menuitem">
<em>Date</em>: Mon, 27 Nov 2006 18:52:28 +0100</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00206.html">20061127-175227.sv7147.87712@gna.org</a>&gt;</li>
<li class="menuitem">
<em>References</em>: </li>
<li class="menuitem">
<em>User-agent</em>: Mozilla/5.0 (X11; U; Linux i686; en-US;	rv:1.8.1) Gecko/20061120 Firefox/2.0</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Sébastien Morin</strong> on November 27, 2006 - 18:52:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">

URL:
  &lt;<a  href="http://gna.org/bugs/?7863">http://gna.org/bugs/?7863</a>&gt;

                 Summary: model_selection('AIC', run, runs=self.runs) in the
script full_analysis.py shoots error
                 Project: relax
            Submitted by: semor
            Submitted on: Monday 11/27/2006 at 17:52
                Category: relax's source code
                Severity: 4 - Important
                Priority: 5 - Normal
                  Status: None
                 Privacy: Public
             Assigned to: None
         Originator Name: 
        Originator Email: 
             Open/Closed: Open
         Discussion Lock: Any
                 Release: Repository: 1.2 line
        Operating System: GNU/Linux

    _______________________________________________________

Details:

</pre><blockquote class="blockquote"><pre style="margin: 0em;">From the 1.2 line at revision 2887... 
</pre></blockquote><pre style="margin: 0em;">

When attempting to make the final optimization (with the full_analysis.py
script), I get an error (after a few seconds) which seems to arise from the
definition of the run data in the file generic_fns/model_selection.py :


Traceback (most recent call last):
  File &quot;/usr/local/bin/relax&quot;, line 454, in ?
    Relax()
  File &quot;/usr/local/bin/relax&quot;, line 166, in __init__
    self.interpreter.run()
  File &quot;/usr/local/packages/relax/prompt/interpreter.py&quot;, line 213, in run
    run_script(intro=self.relax.intro_string, local=self.local,
script_file=self.relax.script_file, quit=1)
  File &quot;/usr/local/packages/relax/prompt/interpreter.py&quot;, line 388, in
run_script
    console.interact(intro, local, script_file, quit)
  File &quot;/usr/local/packages/relax/prompt/interpreter.py&quot;, line 340, in
interact_script
    execfile(script_file, local)
  File &quot;./full_analysis_SEMOR_FINAL_200_auto_check.py&quot;, line 564, in ?
    Main(self.relax)
  File &quot;./full_analysis_SEMOR_FINAL_200_auto_check.py&quot;, line 282, in
__init__
    self.model_selection(run='final', write_flag=0)
  File &quot;./full_analysis_SEMOR_FINAL_200_auto_check.py&quot;, line 496, in
model_selection
    model_selection('AIC', run, runs=self.runs)
AttributeError: Main instance has no attribute 'runs'





    _______________________________________________________

Reply to this item at:

  &lt;<a  href="http://gna.org/bugs/?7863">http://gna.org/bugs/?7863</a>&gt;

_______________________________________________
  Message sent via/by Gna!
  <a  href="http://gna.org/">http://gna.org/</a>



</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00209" href="msg00209.html">[bug #7863] model_selection('AIC', run,	runs=self.runs) in the script full_analysis.py shoots error</a></strong>
<ul><li><em>From:</em> Edward d Auvergne</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Thu Nov 30 09:20:18 2006</div>  
</body>
</html>
