<!-- MHonArc v2.6.16 -->
<!--X-Subject: [bug #12409] Failure of the final stage of the 'full_analysis.py'	script. -->
<!--X-From-R13: Sqjneq q  Ohiretar <@A&#45;DSBZK.W@HOZWR&#45;ORRDSEENtan.bet> -->
<!--X-Date: Sun, 05 Oct 2008 13:09:30 +0200 -->
<!--X-Message-Id: 20081005&#45;110929.sv2782.10819@gna.org -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>[bug #12409] Failure of the final stage of the 'full_analysis.py'	script. -- October 05, 2008 - 13:09</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />[bug #12409] Failure of the final stage of the 'full_analysis.py'	script.</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00011" class="tabs">Index by Date</a> | <a href="threads.html#00011" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00010.html">Date Prev</a>] [<a href="msg00012.html">Date Next</a>] [<a href="msg00010.html">Thread Prev</a>] [<a href="msg00012.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: Edward d  Auvergne &lt;edward@xxxxxxxxxxxxx&gt;, relax-devel@xxxxxxx</li>
<li class="menuitem">
<em>Date</em>: Sun, 05 Oct 2008 13:09:30 +0200</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00011.html">20081005-110929.sv2782.10819@gna.org</a>&gt;</li>
<li class="menuitem">
<em>References</em>: </li>
<li class="menuitem">
<em>User-agent</em>: Mozilla/5.0 (X11; U; Linux i686 (x86_64); en-US;	rv:1.9.0.1) Gecko/2008070206 Firefox/3.0.1</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Edward d Auvergne</strong> on October 05, 2008 - 13:09:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">

URL:
  &lt;<a  rel="nofollow" href="http://gna.org/bugs/?12409">http://gna.org/bugs/?12409</a>&gt;

                 Summary: Failure of the final stage of the
'full_analysis.py' script.
                 Project: relax
            Submitted by: bugman
            Submitted on: Sunday 10/05/2008 at 11:09
                Category: relax's source code
                Severity: 4 - Important
                Priority: 7 - High
                  Status: None
                 Privacy: Public
             Assigned to: bugman
         Originator Name: 
        Originator Email: 
             Open/Closed: Open
         Discussion Lock: Any
                 Release: 1.3.1
        Operating System: All systems

    _______________________________________________________

Details:

When attempting the 'final' stage, an error occurs when loading the PDB file
upon reading of the results file.  The error message is:

relax&gt; results.read(file='results', dir='prolate/round_6/opt')
Opening the file 'prolate/round_6/opt/results.bz2' for reading.
Traceback (most recent call last):
  File &quot;/media/disk/relax/relax-1.3/relax&quot;, line 408, in &lt;module&gt;
    Relax()
  File &quot;/media/disk/relax/relax-1.3/relax&quot;, line 125, in __init__
    self.interpreter.run(self.script_file)
  File &quot;/media/disk/relax/relax-1.3/prompt/interpreter.py&quot;, line 270, in run
    return run_script(intro=self.__intro_string, local=self.local,
script_file=script_file, quit=self.__quit_flag,
show_script=self.__show_script, raise_relax_error=self.__raise_relax_error)
  File &quot;/media/disk/relax/relax-1.3/prompt/interpreter.py&quot;, line 531, in
run_script
    return console.interact(intro, local, script_file, quit,
show_script=show_script, raise_relax_error=raise_relax_error)
  File &quot;/media/disk/relax/relax-1.3/prompt/interpreter.py&quot;, line 427, in
interact_script
    execfile(script_file, local)
  File &quot;full_analysis_final.py&quot;, line 642, in &lt;module&gt;
    Main(self.relax)
  File &quot;full_analysis_final.py&quot;, line 325, in __init__
    results.read(file='results', dir=model + '/round_' + `self.round` +
'/opt')
  File &quot;/media/disk/relax/relax-1.3/prompt/results.py&quot;, line 102, in read
    results.read(file=file, directory=dir)
  File &quot;/media/disk/relax/relax-1.3/generic_fns/results.py&quot;, line 114, in
read
    read_function = ds.from_xml(file, dir=directory)
  File &quot;/media/disk/relax/relax-1.3/data/__init__.py&quot;, line 185, in from_xml
    self[self.current_pipe].from_xml(relax_node, dir=dir)
  File &quot;/media/disk/relax/relax-1.3/data/pipe_container.py&quot;, line 164, in
from_xml
    self.structure.from_xml(str_nodes[0], dir=dir)
  File &quot;/media/disk/relax/relax-1.3/generic_fns/structure/api_base.py&quot;, line
269, in from_xml
    loaded = self.load_pdb(file_path=self.file[i], model=None,
struct_index=i)
  File &quot;/media/disk/relax/relax-1.3/generic_fns/structure/scientific.py&quot;,
line 561, in load_pdb
    self.add_struct(name=name, model=model, file=file, path=path,
str=data_pipe.structure.structural_data[i], struct_index=struct_index)
IndexError: list index out of range


This problem has also been caught by the new test_load_scientific_results()
system test.  Its output when failing is:

======================================================================
FAIL: Load the PDB file using the information in a results file (using the
Scientific python structural object).
----------------------------------------------------------------------

relax&gt; pipe.create(pipe_name='mf', pipe_type='mf')

relax&gt; results.read(file='str_scientific',
dir='/data/relax/relax-1.3/test_suite/shared_data/structures')
Opening the file
'/data/relax/relax-1.3/test_suite/shared_data/structures/str_scientific.bz2'
for reading.
RelaxWarning: The structure file 'Ap4Aase_res1-12.pdb' cannot be found in the
current directory or the directory of the results file.
Traceback (most recent call last):
  File &quot;/data/relax/relax-1.3/test_suite/system_tests/structure.py&quot;, line
113, in test_load_scientific_results
    self.assert_(len(cdp.structure.structural_data))
AssertionError

----------------------------------------------------------------------


This is specific to the Scientific python structural object and doesn't
affect the alternative internal structural object.




    _______________________________________________________

Reply to this item at:

  &lt;<a  rel="nofollow" href="http://gna.org/bugs/?12409">http://gna.org/bugs/?12409</a>&gt;

_______________________________________________
  Message sent via/by Gna!
  <a  rel="nofollow" href="http://gna.org/">http://gna.org/</a>



</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00012" href="msg00012.html">[bug #12409] Failure of the final stage of the 'full_analysis.py'	script.</a></strong>
<ul><li><em>From:</em> Edward d Auvergne</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Sun Oct 05 21:20:51 2008</div>  
</body>
</html>
