<!-- MHonArc v2.6.16 -->
<!--X-Subject: Re: Error when running full_analysis.py script -->
<!--X-From-R13: "Sqjneq q'Ohiretar" <rqjneqNaze&#45;erynk.pbz> -->
<!--X-Date: Tue, 27 Oct 2009 11:02:08 +0100 -->
<!--X-Message-Id: 7f080ed10910270301r6ca3c685t4a968772140996dd@mail.gmail.com -->
<!--X-Content-Type: text/plain -->
<!--X-Reference: 20091005161313.f3715bbf@mail.ccrc.uga.edu -->
<!--X-Reference: 7f080ed10910060031l7b095e79q9d804bdebbe23204@mail.gmail.com -->
<!--X-Reference: 12A9D1A2CF9D4536985EA794893504B7@Mercurio -->
<!--X-Reference: D4A2FB2CF9A04EF28BC6DB4A3EC37A47@Mercurio -->
<!--X-Reference: 4ADF56D6.6080306@ulaval.ca -->
<!--X-Reference: E45CDDF4A4E54B34A36BFBA62E6BFF20@Mercurio -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Re: Error when running full_analysis.py script -- October 27, 2009 - 11:02</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Re: Error when running full_analysis.py script</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00012" class="tabs">Index by Date</a> | <a href="threads.html#00012" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00011.html">Date Prev</a>] [<a href="msg00013.html">Date Next</a>] [<a href="msg00009.html">Thread Prev</a>] [<a href="msg00014.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: Tiago Pais &lt;tpais@xxxxxxxxxxx&gt;</li>
<li class="menuitem">
<em>Date</em>: Tue, 27 Oct 2009 11:01:59 +0100</li>
<li class="menuitem">
<em>Cc</em>: relax-users@xxxxxxx</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00012.html">7f080ed10910270301r6ca3c685t4a968772140996dd@mail.gmail.com</a>&gt;</li>
<li class="menuitem">
<em>References</em>: &lt;20091005161313.f3715bbf@xxxxxxxxxxxxxxxxx&gt;	&lt;7f080ed10910060031l7b095e79q9d804bdebbe23204@xxxxxxxxxxxxxx&gt;	&lt;<a href="msg00006.html">12A9D1A2CF9D4536985EA794893504B7@Mercurio</a>&gt;	&lt;<a href="msg00007.html">D4A2FB2CF9A04EF28BC6DB4A3EC37A47@Mercurio</a>&gt;	&lt;4ADF56D6.6080306@xxxxxxxxx&gt;	&lt;<a href="msg00009.html">E45CDDF4A4E54B34A36BFBA62E6BFF20@Mercurio</a>&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Edward d'Auvergne</strong> on October 27, 2009 - 11:02:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Dear Tiago,

This is a hard one to catch.  I have just added a function to this
script to check the validity of the user variables
(<a  rel="nofollow" href="http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=9794&amp;view=markup">http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=9794&amp;view=markup</a>).
 This should give better error messages specifically identifying the
problem.  For this second issue you are having, it is a little hard to
see what the problem is.  Would you be able to supply a little more
information.  For example the version of relax you are using, the full
error message, how you have executed the full_analysis.py script and
at what stage you are up to, etc.  With more information, I should be
able to track down the issue.

Cheers,

Edward



2009/10/22 Tiago Pais &lt;tpais@xxxxxxxxxxx&gt;:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">Hi Sebastien,
The thing is it was not exactly an error of the script. In the line 639 you
have to adjust the script so that it agrees with the format of the function
that you have used in line 174 &quot;Relax_Data=[...&quot;. If in line 174 you
describe the data sets with only three parameters (e.g.[Rilabel, freq,
file]) then, in line 639 you have to adapt the function so that the program
reads only three sets of parameters (e.g. relax_data.read(data[0], data[1],
data[2], data[3]) while in the original file was set to read 13.
This is beginners' stuff, but that's exactly what I am with respect to RELAX
and PYTHON, so it may be usefull for other beginners.

However, I still have not managed to run the script to the end. At the
moment I am stuck with yet another error message: AttributeError:
'PipeContainer' object has no attribute 'diff_tensor'

If anyone can help me and avoid that I loose time with this probably easy to
solve error, please do.
Thanks
Tiago P

-----Original Message-----
From: Sébastien Morin [<a  rel="nofollow" href="mailto:sebastien.morin.1@xxxxxxxxx">mailto:sebastien.morin.1@xxxxxxxxx</a>]
Sent: quarta-feira, 21 de Outubro de 2009 19:46
To: Tiago Pais
Cc: 'Edward d'Auvergne'; 'Boaz Shapira'; relax-users@xxxxxxx
Subject: Re: Error when running full_analysis.py script

Dear Tiago,

Just for the logs, could you tell us what was the problem ?

Regards,


Sébastien


Tiago Pais wrote:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">Ok, managed to solve this already.
Cheers
Tiago

-----Original Message-----
From: relax-users-bounces@xxxxxxx [<a  rel="nofollow" href="mailto:relax-users-bounces@xxxxxxx">mailto:relax-users-bounces@xxxxxxx</a>] On
Behalf Of Tiago Pais
Sent: quarta-feira, 21 de Outubro de 2009 15:53
To: 'Edward d'Auvergne'; 'Boaz Shapira'
Cc: relax-users@xxxxxxx
Subject: Error when running full_analysis.py script

Dear all,
I am using 15N relaxation data previously analyzed to test some of the
scripts available in Relax to make sure that I am using it correctly.
However, I get the following error message when running the sample script
full_analysis.py: &quot;List Index out of Range&quot;
Below is &quot;print screen&quot; where the error shows up at the bottom:

&quot;None       149        Q          None       None

relax&gt; spin.name(spin_id=None, name='N', force=False)
Traceback (most recent call last):
  File &quot;/usr/local/bin/relax&quot;, line 418, in &lt;module&gt;
    Relax()
  File &quot;/usr/local/bin/relax&quot;, line 127, in __init__
    self.interpreter.run(self.script_file)
  File &quot;/usr/local/relax/prompt/interpreter.py&quot;, line 276, in run
    return run_script(intro=self.__intro_string, local=self.local,
script_file=script_file, quit=self.__quit_flag,
show_script=self.__show_script,
raise_relax_error=self.__raise_relax_error)
  File &quot;/usr/local/relax/prompt/interpreter.py&quot;, line 537, in run_script
    return console.interact(intro, local, script_file, quit,
show_script=show_script, raise_relax_error=raise_relax_error)
  File &quot;/usr/local/relax/prompt/interpreter.py&quot;, line 433, in
interact_script
    execfile(script_file, local)
  File &quot;full_analysis.py&quot;, line 671, in &lt;module&gt;
    Main(self.relax)
  File &quot;full_analysis.py&quot;, line 220, in __init__
    self.multi_model(local_tm=True)
  File &quot;full_analysis.py&quot;, line 639, in multi_model
    relax_data.read(data[0], data[1], data[2], data[3], data[4], data[5],
data[6], data[7], data[8], data[9], data[10], data[11],
data[12])
IndexError: list index out of range&quot;

I can't understand if the error relates to the last command listed,
</pre></blockquote><pre style="margin: 0em;">actually
</pre><blockquote class="blockquote"><pre style="margin: 0em;">I can't understand the command given in this line (639) - what is it
</pre></blockquote><pre style="margin: 0em;">suppose
</pre><blockquote class="blockquote"><pre style="margin: 0em;">to do?

Best regards
TiagoP


_______________________________________________
relax (<a  rel="nofollow" href="http://nmr-relax.com">http://nmr-relax.com</a>)

This is the relax-users mailing list
relax-users@xxxxxxx

To unsubscribe from this list, get a password
reminder, or change your subscription options,
visit the list information page at
<a  rel="nofollow" href="/mail.gna.org/listinfo/relax-users">https://mail.gna.org/listinfo/relax-users</a>


_______________________________________________
relax (<a  rel="nofollow" href="http://nmr-relax.com">http://nmr-relax.com</a>)

This is the relax-users mailing list
relax-users@xxxxxxx

To unsubscribe from this list, get a password
reminder, or change your subscription options,
visit the list information page at
<a  rel="nofollow" href="/mail.gna.org/listinfo/relax-users">https://mail.gna.org/listinfo/relax-users</a>

</pre></blockquote><pre style="margin: 0em;">


--
Sébastien Morin
PhD Student
S. Gagné NMR Laboratory
Université Laval &amp; PROTEO
Québec, Canada


</pre></blockquote><pre style="margin: 0em;">


</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00015" href="msg00015.html">RE: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
<li><strong><a name="00014" href="msg00014.html">RE: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<ul><li><strong>References</strong>:
<ul>
<li><strong><a name="00004" href="msg00004.html">Re: SRLS</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
<li><strong><a name="00006" href="msg00006.html">Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
<li><strong><a name="00007" href="msg00007.html">RE: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
<li><strong><a name="00008" href="msg00008.html">Re: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Sébastien Morin</li></ul></li>
<li><strong><a name="00009" href="msg00009.html">RE: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
</ul></li></ul>
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Tue Oct 27 13:40:15 2009</div>  
</body>
</html>
